### ISSUE TITLE
Sync doesn't guarantee to see the last write

### ISSUE THREAD

**Issue by cyriltovena** [polarsignals/frostdb#112]
While trying to add back the write benchmark I realized Sync doesn't guarantee to see the last write even if it has already returned.

see https://github.com/polarsignals/frostdb/pull/111

I'm guessing this is a bug, but may be that's not a given guarantee.

**Comment by cyriltovena** [comment]
This diff seems to fix the issue but I'm not sure this is correct.

```diff
diff --git a/db.go b/db.go
index 0a0ad01..2f2251f 100644
--- a/db.go
+++ b/db.go
@@ -196,7 +196,7 @@ func (p *DBTableProvider) GetTable(name string) logicalplan.TableReader {
 
 // beginRead returns the high watermark. Reads can safely access any write that has a lower or equal tx id than the returned number.
 func (db *DB) beginRead() uint64 {
-       return db.highWatermark.Load()
+       return db.tx.Load()
 }
```

**Comment by cyriltovena** [comment]
Actually it doesn't fix completely the issue only for when I'm running with 10 worker, with 100 I still miss data.

**Comment by brancz** [comment]
A write returning doesn't necessarily mean that it was successful, that it has been completed, nor that the transaction has been released by the isolation mechanism. Replacing the high water mark with the latest transaction ID breaks the atomicity and will cause ripped writes.

Actually even `.Sync()` doesn't guarantee anything else than that there are no compactions currently running, but that doesn't need to mean that the transaction has been released. Seems like we actually need an additional `.WaitForTx` or something like that (and for that to work we also need the write to return its transaction ID).

**Comment by brancz** [comment]
cc @thorfour

**Comment by thorfour** [comment]
https://github.com/polarsignals/frostdb/blob/42eb27a93c4bc694d9ec4848a30c0e5ecdd8efb5/table.go#L528
Sync is intended to ensure that compactions are complete if you control all the writers. It's basically only useful for unit tests. 

> Actually even .Sync() doesn't guarantee anything else than that there are no compactions currently running, but that doesn't need to mean that the transaction has been released. Seems like we actually need an additional .WaitForTx or something like that (and for that to work we also need the write to return its transaction ID).

We have all this:
https://github.com/polarsignals/frostdb/blob/main/db.go#L222
You can use wait to wait for the given tx ID to be marked complete with the returned tx id from `InsertBuffer`: https://github.com/polarsignals/frostdb/blob/main/table.go#L243

**Comment by cyriltovena** [comment]
Sounds good I'll give it a go

**Comment by brancz** [comment]
🙈 I could have sworn we already had that, but couldn't find it, thanks Thor!
