### ISSUE TITLE
Wrap database logger with database name

### ISSUE THREAD

**Issue by metalmatze** [polarsignals/frostdb#133]
It would be great to pass down the logger into the database and automatically add the database name as key-value pair:
https://github.com/polarsignals/frostdb/blob/b2cc5b02f387b5a9a8da72cb20e01deaf13c3d3e/db.go#L238

Something like the following would be great:
```
log.WithPrefix(s.logger,"db",name)
```

**Comment by brancz** [comment]
ah whops we do this for the metrics registry but not for this haha

**Comment by metalmatze** [comment]
If anyone seeing this wants to have a FrostDB contribution, this should be fairly easy to do! :relaxed:
