### ISSUE TITLE
Update TableReader interface to return (*Schema,error)?

### ISSUE THREAD

**Issue by metalmatze** [polarsignals/frostdb#134]
It might make sense to update the interface to return the error too?
https://github.com/polarsignals/frostdb/blob/b2cc5b02f387b5a9a8da72cb20e01deaf13c3d3e/query/logicalplan/logicalplan.go#L133

Or should this error really just be handled outside the interface? Basically opening that as a question to everyone else as I'm not 100% sure right now.

**Comment by brancz** [comment]
This schema should be passed as configuration when instantiating the table, so it should just be a pointer in the table that's just always there, I don't think there is any way currently for this to error.

**Comment by thorfour** [comment]
I currently have a way for this to error :P so this panic is currently earmarked in what I'm working on.

**Comment by metalmatze** [comment]
Did we happen to update this in one of the PRs? Just making sure we close it if we don't need it anymore.

**Comment by brancz** [comment]
I don’t think we’ve done this. I *think* what Thor referenced we managed to get to work without this.

**Comment by thorfour** [comment]
Yea I ended up not needing to make this change, so I'm just going to close this issue for now
