### ISSUE TITLE
Query path benchmarks

### ISSUE THREAD

**Issue by thorfour** [polarsignals/frostdb#151]
Right now we have a small set of benchmarks that really only benchmark concurrent writers.
It would be good to get some benchmarks around the query path, as well as large database benchmarks etc.

**Comment by brancz** [comment]
There are some query benchmarks in the parca project, those are what I’ve been using for query benchmarking.

**Comment by asubiotto** [comment]
Planning on taking this on. I think adding some benchmarks to FrostDB that represent the cloud OKRs would be pretty useful to get some less noisy benchmarks.
