### ISSUE TITLE
Replace unsafe atomic pointers with Go 1.19 generic pointer

### ISSUE THREAD

**Issue by brancz** [polarsignals/frostdb#157]
We have a bunch of uses of unsafe atomic pointers. Go 1.19 shipped with a generic (type-safe) atomic pointer that we should now use.

https://pkg.go.dev/sync/atomic@go1.19#Pointer

**Comment by Mihai22125** [comment]
Hello, @brancz! Can I work on this?

**Comment by brancz** [comment]
Go ahead!

**Comment by thorfour** [comment]
Completed in https://github.com/polarsignals/frostdb/pull/203
