### ISSUE TITLE
Attempt to use ColumnIndex to answer distinct queries

### ISSUE THREAD

**Issue by brancz** [polarsignals/frostdb#158]
While we already attempt to optimize distinct queries by checking if they are dictionary encoded and only contain a single value, that still causes us to read the page, using the ColumnIndex however, we could avoid reading the page altogether.

**Comment by asubiotto** [comment]
Planning on taking a look at this today

**Comment by asubiotto** [comment]
I've taken a look at the code where the mentioned optimization is and the functions called. Just so we're on the same page, these look to be `distinctColumnsToArrowRecord` all the way down to `writeColumnToArray`. I wanted to clarify the optimization we want to do.

`ColumnIndex` gives us min/max values in that column chunk. Is the optimization you're suggesting basically checking that for a given page, we only call `ReadPage` if its min value == max value and the min/max value == the last read page's max value?
