### ISSUE TITLE
Remove PrefixedBucket

### ISSUE THREAD

**Issue by brancz** [polarsignals/frostdb#159]
The upstream `objstore` dependency we use now implements an identical prefixing mechanism (unsurprisingly since we contributed it), so we should get rid of the one in this repository:

https://github.com/polarsignals/frostdb/blob/42eb27a93c4bc694d9ec4848a30c0e5ecdd8efb5/bucket.go

**Comment by manojVivek** [comment]
Should we change the `NewPrefixedBucket` func to wrap `objstore` internally or remove `bucket.go` altogether and let the caller pass a bucket created from `objstore.NewPrefixedBucket`?

**Comment by brancz** [comment]
I would say to replace our implementation entirely with the one from `objstore`. If you want to pick this up do chat with @asubiotto as he was thinking of tackling this as well.
