### ISSUE TITLE
Support more aggregation functions

### ISSUE THREAD

**Issue by yeya24** [polarsignals/frostdb#177]
Right now frostdb only has limited support for aggregation functions. For observability and analytical purpose, more aggregation functions should be supported to cover more use cases. For me, I have the requirement to support aggregations like `count`, `average` and `quantile`. 

I opened this as an umbrella issue to track the support to other aggregation functions. For aggregation functions to support, feel free to add your use case. For a good start, probably we can take a look at https://prometheus.io/docs/prometheus/latest/querying/operators/#aggregation-operators and https://duckdb.org/docs/sql/aggregates.

- [x] Support `count` aggregate function. PR: https://github.com/polarsignals/frostdb/pull/176
- [ ] Support `quantile` aggregate function
- [ ] Support `average` aggregate function

**Comment by palash25** [comment]
hi @yeya24 are you working on either average or quantile functions?

**Comment by yeya24** [comment]
@palash25 Please go ahead.
