### ISSUE TITLE
what is aggregate meaning?

### ISSUE THREAD

**Issue by zdyj3170101136** [polarsignals/frostdb#200]
here is parca code:
it is very confusing
![截屏2022-09-19 上午10 21 33](https://user-images.githubusercontent.com/52686065/190940282-193aaea0-1958-4929-a384-acd5ecb9e4e7.png)

is the aggregate meaning sql like:
```
select sum(value), timestamp, labels
from table
group by timestamp, labels
```

**Comment by asubiotto** [comment]
Hello,

Currently in FrostDB we only support aggregate functions with a single aggregation expression and multiple group expressions:
https://github.com/polarsignals/frostdb/blob/687469d4f7ea26aeb632077b374476a792980c4f/query/engine.go#L15

So the above snippet you posted is equivalent to:
```
SELECT sum(value) GROUP BY labels, timestamp
```
