### ISSUE TITLE
Make concurrency configurable at runtime

### ISSUE THREAD

**Issue by metalmatze** [polarsignals/frostdb#209]
> If we decide to make concurrency configurable at runtime (which we might want to do based on load), I think this will create an unnecessary synchronizer if we have concurrency == 1 for any reason. What do you think of creating a struct with more planning state to make more informed decisions of what to plan? For example, store some sort of notion of whether we *have* to plan a synchronizer. Maybe it's fine to also check `len(phyPlans)`, but it seems to me like this state complexity will start to balloon. This struct I suggest might also be useful for more planning information (e.g. ordering column guarantees)

_Originally posted by @asubiotto in https://github.com/polarsignals/frostdb/pull/202#discussion_r976283462_

**Comment by asubiotto** [comment]
I think @thorfour fixed this recently, right?

**Comment by thorfour** [comment]
I tried, but it ended up being more of a can of worms since our aggregations don't work at concurrency 1. And in testing in prod I ran into additional issues not caught by the unit tests. Needs revisiting. 

https://github.com/polarsignals/frostdb/pull/657 for future reference

**Comment by thorfour** [comment]
Removing stale because this is still currently broken.

**Comment by thorfour** [comment]
Closing this in favor of #769
