### ISSUE TITLE
Mock out TableProvider and implement a logicalplan.TableReader that returns records directly

### ISSUE THREAD

**Issue by asubiotto** [polarsignals/frostdb#217]
It'd be nice to be able to push arrow records directly into a query plan. Recently, I came across this need during testing, think it would be nice for benchmarking operators with a speed of light scan layer, and also believe it could be useful in other scenarios.

To do this, I think we're going to want to put an interface on top of `frostdb.DBTableProvider`, where there would be an implementation that would return a normal table through `GetTable`, and another one that would return a `logicalplan.TableReader` (already an interface) that would be passed into the DB somehow with a reference to records to return when `Iterator` is called on it.

**Comment by brancz** [comment]
Makes sense!

**Comment by MadhavJivrajani** [comment]
Would it be okay if I gave this a shot?

**Comment by asubiotto** [comment]
@MadhavJivrajani of course!
