### ISSUE TITLE
Move operator tests to logic tests

### ISSUE THREAD

**Issue by asubiotto** [polarsignals/frostdb#226]
A datadriven logic testing framework was recently added in https://github.com/polarsignals/frostdb/pull/211. Slowly but surely, it would be nice to move our operator tests to this logic testing framework to promote readability and conciseness. #255 does this for the distinct operator. This issue can be closed once the following tests have been moved over:
- [ ] aggregate_test.go
- [x] filter_test.go

**Comment by bitethecode** [comment]
@asubiotto Can you assign this to me?

**Comment by asubiotto** [comment]
Sure!

**Comment by bitethecode** [comment]
@asubiotto Thanks!!!

**Comment by palash25** [comment]
hi @bitethecode are you still working on this? if not then i would like to pick this up if that's ok with you

**Comment by asubiotto** [comment]
Hi @palash25, are you still interested in working on this? I can reassign to you given that we haven't heard back.

**Comment by asubiotto** [comment]
No problem! Thanks for giving it a shot. @palash25 assigned to you. Feel free to use https://github.com/polarsignals/frostdb/pull/225 as a guide.

**Comment by palash25** [comment]
thanks for assigning i will look into it this weekend

**Comment by palash25** [comment]
as i have already submitted 2 PRs, i would like to be unassigned so that someone else can try to convert the remaining go tests

**Comment by asubiotto** [comment]
I think there are still some tests to be moved (notably the projection tests in `aggregate_test.go`). I believe #302 will likely address this, but reopening to track.
