### ISSUE TITLE
Compaction memory usage spike

### ISSUE THREAD

**Issue by asubiotto** [polarsignals/frostdb#239]
We see some unexpected memory spikes during compaction (this is a local demo instance scraping itself):
![](https://cdn.discordapp.com/attachments/963045173535834182/1034366857869799454/unknown.png)
In the graph above, there is a ~1GB memory spike that is attributed to compaction. Matching this with the compaction that occurred during this time in the logs (debug level), we get:
```
level=debug db=parca name=parca ts=2022-10-25T06:57:11.229938Z caller=compaction.go:187 msg="compaction complete" duration=3.117003833s l0Before="[sz=21 MiB,cnt=483]" l1Before="[sz=4.3 MiB,cnt=1]" l1After="[sz=5.9 MiB,cnt=1]" overlaps=1 splits=0
```
So this ~1GB of allocations was a result of merging 483 parts that sum up to 21 MiB and 1 4.3MiB part. Given parquet decompression, we do expect memory usage to be higher than the l0+l1 size, but 1GB seems like too much. One theory of what is going on is that buffer pooling is not working as expected in parquet (https://github.com/segmentio/parquet-go/issues/372).

**Comment by gernest** [comment]
Has this been resolved yet? I would lie to address it, whether here or on `parquet-go` side, any pointers to lead me in the right direction will be highly appreciated.

**Comment by asubiotto** [comment]
Yes, this has been resolved!
