### ISSUE TITLE
Add support for Projections in logic tests

### ISSUE THREAD

**Issue by thorfour** [polarsignals/frostdb#255]
We recently discovered that the logic tests don't support projections when I implemented projections during aggregations here: https://github.com/polarsignals/frostdb/pull/252

**Comment by asubiotto** [comment]
To implement this, we probably need to add another switch case in the following function: https://github.com/polarsignals/frostdb/blob/e628ed588e1fc41b450e7d25e1cbea6855ea7f00/sqlparse/visitor.go#L48

To figure out what the ast node is, the best way is to step through using a debugger while running a logictest sub test with a projection.

**Comment by palash25** [comment]
could this be solved by iterating over `SelectFields` and applying a projection for each? something like this?

```go
case *ast.FieldList:
		for _, f := range expr.Fields {
			v.builder.Project(f.Expr)
		}
```

**Comment by asubiotto** [comment]
I haven't looked at this closely enough to know, but this would make sense, although `Project` takes multiple expressions so we'd probably want to push them on the expression stack and then pop them all off when encountering a `FieldList` if that makes sense. I'm also wondering about the case when we don't want to call `builder.Project` (i.e. as we currently do).

**Comment by thorfour** [comment]
This was added by https://github.com/polarsignals/frostdb/pull/258
