### ISSUE TITLE
logictests: exec query results with null values returned as whitespace

### ISSUE THREAD

**Issue by palash25** [polarsignals/frostdb#259]
Hmm, I guess it's probably an artifact of the aggregator that doesn't correctly set nulls in the output (and instead sets an empty string). This is probably something to open an issue about as well although it's not too high priority. We can probably merge this as is with at least a comment pointing to the issue.

_Originally posted by @asubiotto in https://github.com/polarsignals/frostdb/pull/257#discussion_r1035904418_

**Comment by palash25** [comment]
in the logictest if a query returns rows with null values the show up as whitestapces. Take this for e.g.

```
createtable schema=default
----

insert cols=(labels.label1, labels.label2, stacktrace, timestamp, value)
value1  null    stack1  1   1
null    value2  stack1  2   2
null    value2  stack1  3   3
----

exec
select sum(value) as value_sum group by labels.label2
----
              1
value2  5
```

the result should be more explicit and should look like this

```
exec
select sum(value) as value_sum group by labels.label2
----
 null      1
value2  5
```

**Comment by asubiotto** [comment]
Worth keeping this open even though it's not high priority

**Comment by thorfour** [comment]
Confirmed this is no longer an issue with the following logic test

```bash
 createtable schema=default
  ----

  insert cols=(labels.label1, labels.label2, stacktrace, timestamp, value)
  value1  null    stack1  1   1
  null    value2  stack1  2   2
  null    value2  stack1  3   3
  ----

  exec
  select sum(value) as value_sum, labels.label2 group by labels.label2
  ----
  5       value2
  1       null
```
