### ISSUE TITLE
Wal replay not correctly decoding schema

### ISSUE THREAD

**Issue by asubiotto** [polarsignals/frostdb#281]
When trying to run some benchmarks on a WAL, the recent schema v2 changes (https://github.com/polarsignals/frostdb/pull/273) cause this error to occur:
```
go test -benchmem -run=^$ -bench BenchmarkQuery github.com/polarsignals/frostdb -test.timeout 24h -count 10 -v
goos: darwin
goarch: arm64
pkg: github.com/polarsignals/frostdb
BenchmarkQuery
    bench_test.go:119: replaying WAL
    bench_test.go:120:
        	Error Trace:	bench_test.go:120
        	Error:      	Received unexpected error:
        	            	second WAL replay: call replay handler: insert buffer into block: failed to get writer: expected 0 dynamic column names, got 3
        	Test:       	BenchmarkQuery
```

I tracked this down to the fact that neither of the cases in this switch case is being hit: https://github.com/polarsignals/frostdb/blob/fb9896e4077d42a2a36d35acd4d292f5aa261b26/db.go#L432-L443
and there is no `default` catchall that errors out. This seems like in an empty schema being created, thus no dynamic columns.

cc @thorfour

**Comment by brancz** [comment]
we probably want to extract that into a separate function and not share the `def` variable, then the compiler would have also told us it's unhandled.

**Comment by asubiotto** [comment]
Agreed, I also think there's an identical block further down the file.

**Comment by thorfour** [comment]
Good catch

**Comment by asubiotto** [comment]
I'm still having issues running `BenchmarkQuery` with the latest frost on a WAL from before the schema change:
```
BenchmarkQuery
    bench_test.go:119: replaying WAL
    bench_test.go:120:
        	Error Trace:	bench_test.go:120
        	Error:      	Received unexpected error:
        	            	second WAL replay: call replay handler: initialize schema: proto: mismatched message type: got "frostdb.schema.v1alpha1.Schema", want "parca"
        	Test:       	BenchmarkQuery
```
