### ISSUE TITLE
frostdb: persist blocks based on time

### ISSUE THREAD

**Issue by asubiotto** [polarsignals/frostdb#342]
We currently persist table blocks based on the amount of data accumulated in memory. When persisting, an entry is written to the WAL after uploading the table block to object storage and attempt to truncate WAL entries. In https://github.com/polarsignals/frostdb/pull/340, we noticed that if a database had two tables, a small one (call it A) and a big one (call it B), even though B would persist blocks, all of B's records could not be truncated from the WAL if A remains small enough that it is never persisted. This makes sense given that a WAL is shared across tables, so insert records are interleaved. If we were to truncate the WAL when one of B's blocks is persisted, we would lose all the records inserted into A up to that point.

This issue proposes to persist based on time in addition to size. The rule should be something like "if no new data has been inserted in x timeframe, persist the block", this would allow the WAL to be truncated safely and therefore reduce WAL storage size and replay time.

**Comment by asubiotto** [comment]
I implemented this in https://github.com/polarsignals/frostdb/tree/alfonso-bsweeper, but I realized that the problem is not that no new data is inserted in x window. It's more that the smaller table just has a tiny rate of growth. Maybe it should be up to the user to define a separate active table block size?

**Comment by brancz** [comment]
We could implement a similar behavior to Prometheus, which doesn't flush based on time passed, but rather the maximum amount of time between the smallest and largest timestamp in a block of data. This trigger could be something that is defined on the table level.

**Comment by asubiotto** [comment]
Closing in favor of #345
