### ISSUE TITLE
Support grouping multiple rows of first match in an interval

### ISSUE THREAD

**Issue by metalmatze** [polarsignals/frostdb#347]
Right now Parca queries FrostDB for all the timestamps and on the server side chooses to ignore metric samples when a sample has been found in the step's bucket.

https://github.com/parca-dev/parca/blob/ed90dbeb684186e9cdb295bc0f62c723ed3c5a9f/pkg/parcacol/querier.go#L571-L579

This isn't ideal since the data is still queried...

FrostDB should add support to find all rows for a bucket of interval and only then start aggregating. 

The row data would look like this:
| timestamp 	| stacktrace 	| value 	|
|-----------	|------------	|-------	|
| 1         	| stack1     	| 3     	|
| 1         	| stack2     	| 5     	|
| 1         	| stack3     	| 8     	|
| 2         	| stack1     	| 2     	|
| 2         	| stack2     	| 3     	|

What we want. We want to only return the sum(value) for the first timestamp we find in the bucket that ranges from 0-9. 
So what we want as a result is:
| timestamp 	| sum(value) 	|
|-----------	|------------	|
| 1         	| 16          	|

What we currently get is however the very first row that falls within that bucket `(1, stack1, 3)` and then the sum of it's value, which is basically a noop:
| timestamp 	| sum(value) 	|
|-----------	|------------	|
| 1         	| 3          	|

**Comment by metalmatze** [comment]
This issue is especially bad for Parca itself. On our cloud with the aggregate_view table, it shouldn't be such a bad problem for now.

**Comment by albertlockett** [comment]
@metalmatze As far as I an tell the `Duration` aggregation does what we want. I added a test to demonstrate.
https://github.com/polarsignals/frostdb/pull/503/files

That said, I think this is different than what we do here in parca, where we take the first result in the interval.
https://github.com/parca-dev/parca/issues/2598

I'm wondering if maybe what we want is a `First` aggregation instead like this?
https://github.com/polarsignals/frostdb/pull/504
