### ISSUE TITLE
Record schema changes in WAL

### ISSUE THREAD

**Issue by thorfour** [polarsignals/frostdb#361]
https://github.com/polarsignals/frostdb/blob/e98d6bfeb8bf59dbb593d2ac663058bb4d1fb8ab/db.go#L638

The Table function accepts a table config with a new schema, but never applies the schema to the table.  This can cause a panic during wal replays where the wal will replay the writes for the new schema under the old schema because the schema change was never recorded.

We need to 
- check if the passed in schema was different than what the table has, if it is, update the schema to the new schema.
- Record in the WAL a schema change event.
- During replay if schema change event detected, update the table schema with saved schema

**Comment by asubiotto** [comment]
Fixed by #383
