### ISSUE TITLE
Labels not respected during query

### ISSUE THREAD

**Issue by thorfour** [polarsignals/frostdb#387]
*NOTE* this is an experimental arrow ingestion bug only

If we query for a label that doesn't exist we'll get back all results as the label isn't respected. I believe this is due to the fact that we apply these label queries as physical projections when converting from parquet to arrow, but since we skip this step during the table scan I believe we erronously return data that we otherwise shouldn't.

**Comment by asubiotto** [comment]
Doesn't `dropPendingBlock`: https://github.com/polarsignals/frostdb/blob/316e3ce05e2fad8404a810ddabbfb6488ee2891b/table.go#L380

do this?

**Comment by thorfour** [comment]
I can't get this to recreate; going to close for now.
