### ISSUE TITLE
Arrow records not released on block rotation

### ISSUE THREAD

**Issue by thorfour** [polarsignals/frostdb#388]
Arrow records are not released when a block is rotated out. We need to ensure we aren't leaking resources related to arrow records.

We should walk all parts in a completed block and release any records found there.

**Comment by asubiotto** [comment]
Doesn't `dropPendingBlock`: https://github.com/polarsignals/frostdb/blob/316e3ce05e2fad8404a810ddabbfb6488ee2891b/table.go#L380

do this?

**Comment by thorfour** [comment]
ah ha! Thank you; I totally missed that. Closing as this is implemented already.
