### ISSUE TITLE
snapshots: refactor into a separate package

### ISSUE THREAD

**Issue by asubiotto** [polarsignals/frostdb#389]
When writing the snapshot code, I believed that it was too intertwined with database internals to be a separate package. However, we could use an API of the style of the `wal` to use a callback to load the state into the database. This issue tracks exploring that refactor.

**Comment by asubiotto** [comment]
Still relevant although this is not high priority

**Comment by thorfour** [comment]
I'm going to close this in favor of #722 which encompasses this
