### ISSUE TITLE
Fix Release() arrow callbacks

### ISSUE THREAD

**Issue by thorfour** [polarsignals/frostdb#403]
Our usage of Release of arrow records during callback is inconsistent. If operators are utilized they won't release the callback record, but will create a new one which the final callback can release. 

However if there is no operators and it's just straight iteration then a release on the final callback will cause too many releases to occur.

This is easy to reproduce by running unit tests with `-tags assert`

The final callback should always be able to safely release the given record.

We should detect this automatically but adding `-tags assert` to our github workflow.

**Comment by brancz** [comment]
Oh cool didn’t know about the assert tag!

**Comment by albertlockett** [comment]
I could take a look at it

**Comment by albertlockett** [comment]
@thorfour I think the issue we're having is us calling HashAggregate's Close() method multiple times (as that's where it releases its arrow records).

For a query like this:
```golang
err = engine.ScanTable("simple_table").
Aggregate(
	[]logicalplan.Expr{
		logicalplan.Sum(logicalplan.Col("value")),
	},
	[]logicalplan.Expr{
		logicalplan.Col("names.first_name"),
	},
).
```

We end up w/ a physical plan like this:
```
     1                           2                                           3                 4
TableScan [concurrent] - HashAggregate (sum(value) by names.first_name) - Synchronizer - HashAggregate (sum(value) by names.first_name)
                       - HashAggregate (sum(value) by names.first_name) -
   multiple plans ->   ... for each TableScan.plan
                       - HashAggregate (sum(value) by names.first_name) -
 ```
 
 We end up calling the `Close()` method for each of tablescan's plans (2) 
 https://github.com/polarsignals/frostdb/blob/de942d0ce46e8ca34b3f08cc96f3ce61da96f26a/query/physicalplan/physicalplan.go#L125-L129
 
 This in turn will call Synchronizer's (3) `Close` multiple times, which will call HashAggregate's (4) `Close` method mulitple times.
 
 I think it's reasonable for a given step in the physical plan to expect to only have its `Close()` method called once, with the exception of possibly synchronizer. To that end, I think it's reasonable for us to add some logic into synchronizer to call `next.Close()` only once.
 
 What do you think of that plan?

**Comment by thorfour** [comment]
I think that makes a lot of sense. The synchronizer should have the logic to only call close once.

I think when I first wrote this issue there was also an issue with performing a query with no operators. So that may be something to look into as well.

**Comment by albertlockett** [comment]
You were thinking something like this?
```golang
err = engine.ScanTable("simple_table").
  Execute(context.Background(), func(ctx context.Context, r arrow.Record) error {
	  fmt.Printf("%v", r)
	  return nil
  })
```
That actually seems to work alright.

We have a number of tests that seem to release the record in the  table iterator callback, which I'll clean up as well
https://github.com/polarsignals/frostdb/blob/de942d0ce46e8ca34b3f08cc96f3ce61da96f26a/table_test.go#L176
