### ISSUE TITLE
*: frostdb does not offer snapshot isolation

### ISSUE THREAD

**Issue by asubiotto** [polarsignals/frostdb#446]
Currently, frostdb does not offer snapshot isolation as our [README says it does](https://github.com/polarsignals/frostdb#snapshot-isolation). Consider the following scenario:
- txns 1, 2, 3 commit. This translates to a single granule with three parts, each with the corresponding transaction.
- A read comes in and uses the high watermark (i.e. txn 3). Data at txn 1,2,3 is returned.
- Meanwhile txn 4 happens, writing a new part with txn 4 to the granule.
- a compaction happens, rewriting all parts in the granule into a single part with txn 4.
- txn 3 at this point could legally perform a read (or even if a new read comes in and wants to perform it at txn 3). If it does so, no data will be returned because the part has a txn id > the read.

To fix this, we should not lose information when compacting data. The new part should maintain the lowest txn id of writes. If a read txn id is contained between the min, max of the txn ids in the part, an error should be returned and a read retried at a higher txn id. Correctly returning data for the transaction will probably cost us too much memory to support. If we think we want to do that, we eventually can.

**Comment by thorfour** [comment]
I think this could be fixed if we moved the tx ids into the tables themselves and putting them into the index. Since that way if a read with txn 3 was happening it would always be happening on the previous index.

The scenario described above happens because tx3 can technically start on the next index. I feel like there  was a bug that happened if we used the highest tx in a compaction, but I can't recall what it was.

**Comment by brancz** [comment]
Then we would need to move WALs to be table based as well and prevent transactions to append to two tables. I feel like database level consistency would be nice to have.

Could we somehow do compaction without obtaining a transaction?

**Comment by asubiotto** [comment]
> I think this could be fixed if we moved the tx ids into the tables themselves and putting them into the index. Since that way if a read with txn 3 was happening it would always be happening on the previous index.

IIUC, doesn't this mean that we would need to store previous index (i.e. full btree) versions?

> Could we somehow do compaction without obtaining a transaction?

I think so, but the problem is not that compaction obtains a new transaction, it's that we store txn ids at a part level, so txn id information is implicitly lost when going from multiple parts => single part. If we keep track of the lowest txn across parts as I suggested in the original post, I think we would at least have correct behavior. Reads would then just retry with a higher txn.

**Comment by thorfour** [comment]
With the replacement of the btree is this issue still relevant?

**Comment by asubiotto** [comment]
Yes, we still compact multiple parts with different txn IDs into a single part with a newer (or even zero) txn ID, making it impossible to have fine-grained reads across this part given a maximum txn id.

**Comment by thorfour** [comment]
Yes however it can no longer read inconsistent data. It's just possible for it to read data that is newer than the read tx.

**Comment by thorfour** [comment]
I propose we remove the concept of read transactions as they aren't providing any benefit but are creating confusion
