### ISSUE TITLE
db: snapshot database on Close

### ISSUE THREAD

**Issue by asubiotto** [polarsignals/frostdb#523]
On database close, we persist all data to object storage and drop WAL and snaphost:
https://github.com/polarsignals/frostdb/blob/9cf45ae4dbdaabcffb32c310bcc5da7d47798e36/db.go#L829-L841

However, when manual block rotation is enabled, we simply close the DB leaving the WAL and snapshots intact (see `shouldPersist` above). The downside of doing this is that on a restart, all WAL entries that were logged after the latest snapshot will need to be replayed. Users can try to mitigate this by increasing the snapshot trigger size to have more frequent snapshots, but I think we should ideally snapshot the database on close so that we can truncate the WAL and only recover from that snapshot on startup.

To do this we need to change `asyncSnapshot` to return a waitgroup so that close can wait for that snapshot. After a snapshot is done, we already have a `reclaimDiskSpace` method on the db that will take care of truncating the WAL.

**Comment by thorfour** [comment]
https://github.com/polarsignals/frostdb/pull/525
