### ISSUE TITLE
Change url in README.md

### ISSUE THREAD

**Issue by cbiale** [polarsignals/frostdb#552]
The url to influxdb_iox: https://github.com/influxdata/influxdb_iox goes to a non-existent page. It could be changed to another or remove the url.

The url to parquet-go can be replaced with that of the current repository https://github.com/parquet-go/parquet-go

**Comment by metalmatze** [comment]
Good find. Feel free to send a PR if you want a contribution. Otherwise, we'll fix in soon.

**Comment by gernest** [comment]
This ticket  can be closed. It was fixed in 35a64796b7a928e2f2aadc4d8d79c0c03542d1d7

**Comment by brancz** [comment]
Thanks for catching that @gernest!
