### ISSUE TITLE
frostdb aggregation function is very strong，but aggregation function only support arrow.INT64, can we support arrow.FLOAT64?

### ISSUE THREAD

**Issue by jicanghaixb** [polarsignals/frostdb#587]
frostdb schema can support column type StorageLayout_TYPE_DOUBLE, but aggregation function can't apply it, can we support it ?

**Comment by asubiotto** [comment]
There's no reason why not. We won't be able to get to this anytime soon but will be happy to review a PR.

**Comment by jicanghaixb** [comment]
thank you for your quick response, aggregation functions is one of the most commonly used abstractions data analysis, float64 is more common than int64 in the field of data analysis, so if  aggregation function can support float64,  frostdb can adapt to a wider range of application scenarios.
