### ISSUE TITLE
[Proposal] Consolidate string column handling

### ISSUE THREAD

**Issue by gernest** [polarsignals/frostdb#640]
String column is currently represented as `*array.String|*array.Binary` . This is not consistent because most cases I have seen `string((*array.Binary).Value(n))`. 

I'm proposing being consistent and use `*array.String` for string column. We can introduce `binary` column and use `*array.Binary` for it if it is necessary.

Only blocker I see is the `Sample` struct

```go
type Sample struct {
	ExampleType string            `frostdb:"example_type,rle_dict,asc(0)"`
	Labels      map[string]string `frostdb:"labels,rle_dict,asc(1),null_first"`
	Stacktrace  []uuid.UUID       `frostdb:"stacktrace,rle_dict,asc(3),null_first"`
	Timestamp   int64             `frostdb:"timestamp,asc(2)"`
	Value       int64             `frostdb:"value"`
}
```

The `Stacktrace` field type  `[]uuid.UUID` has  special handling that resolves to `[]byte`, however this is not used  anywhere else apart from tests. I confirmed it is not in `parca`.

Why do we special handle `[]uuid.UUID` ?  If it is not used anywhere else apart from tests, I suggest we get rid of it as well. Most of `*array.Binary` chunks revolve around this special case.

**Comment by thorfour** [comment]
We used to utilize the `uuid` behavior on cloud. However that hasn't been the case for quite some time. I think it's acceptable to normalize the behavior and remove historical choices that haven't been used in a while.

**Comment by brancz** [comment]
We should check if this is still the case but I remember there being non zero overhead in the rest of the query engine and that’s why we wanted to user to be able to control this.

**Comment by gernest** [comment]
> We should check if this is still the case but I remember there being non zero overhead in the rest of the query engine and that’s why we wanted to user to be able to control this.

What do you mean?  Are you talking about `*array.Binary` vs `*array.String` overhead during query time?

**Comment by gernest** [comment]
Closing this for now.

**Comment by brancz** [comment]
I don’t remember the exact details but this was because there was some overhead when using string columns in Parca’s code that happens after the query engine but ultimately the idea is to have the query engine be extensible and the work that Parca currently does on top will just be a query layer.
