### ISSUE TITLE
Notes on vectorisation

### ISSUE THREAD

**Issue by gernest** [polarsignals/frostdb#660]
The reason I was fascinated with `arrow` is the `vectorization` prospects for timeseries data.

I have noticed we don't capitalize on this with `frostdb` yet. So I think it will an interesting area for me to explore and indulge myself.This is random dump of what I have discovered so far, which is subject to change as I gain more insight on the code base.

### Why we can't `vector` yet ?

- We heavily lean towards `*array.Dictionary`. Our current query engine works well in this regards and its design has been influenced by the need to accommodate  this.
Most of vectorized operations works on `*array.Dictionary`. The only one that does not is `compute.Take`.

- TBD

### What can be vectored ?

```
    (*Column).Eq | equal
 (*Column).NotEq | not_equal
    (*Column).Gt | greater
  (*Column).GtEq | greater_equal
    (*Column).Lt | less
  (*Column).LtEq | less_equal
```

TBD

### Regular Expressions

There is no regex operations on arrays.

**Comment by brancz** [comment]
We don’t support these yet, but any mathematical projections will be able to take advantage of vectorization as well. Eg. `a + b`. We’ve needed these in Parca on several occasions so even if we skip on vectorization for now this is certainly something we should implement. 

Sadly avo doesn’t support arm64 yet (to utilize neon extensions), this is also a reason we haven’t invested in this yet.

**Comment by gernest** [comment]
> Sadly avo doesn’t support arm64 yet (to utilize neon extensions), this is also a reason we haven’t invested in this yet.

With the apple silicon ,  `arm64` is getting some love. Lets hope `arm64` will catchup on `amd64` soon.

Thanks for the feedback. I'm running out of low effort interesting things to work on `frostdb`. You just saved me from going down the rabbit hole!

I am closing this for now.  I will try other things (tests and benchmarks seems like a safe bet)

**Comment by asubiotto** [comment]
Just some additional context: vectorization would be great but I think that currently execution engine overhead is not the bottleneck when running queries, so I don't vectorization would move the global needle much. As an example, I think the parquet -> arrow conversion step has a much larger overhead and there is definitely work to do there (e.g. don't materialize dictionaries in parquet before writing to arrow, not sure if this is even possible).

**Comment by gernest** [comment]
> (e.g. don't materialize dictionaries in parquet before writing to arrow, not sure if this is even possible).

@asubiotto this sounds interesting. Can you expand on this a bit ?

I was experimenting storing and querring `otel` `metrics`, `logs` and `traces`. Due to the sheer volume of data all  `string|[]byte` were represented as dictionary by default.  Initially I was doing `arrow -> parquet`  then `parquet -> arrow` during query time for cold data.    After some benchmarks it became evident  serialising `arrow.Record` with `zstd` gave much better result, at least for the type of work load therefore the smaller saves in `parquet`  weren't worthy. So basically, when I reach granule size I merge compacted parts to a single record and store it as is in cold storage( However I have to maintain a separate index for the whole granule to facilitate using fast searchh and  `min/max` skipping of timestamps  a combination of  `roaring.Bitmap` and ` https://github.com/blevesearch/vellum ), so I didn't need the page wise bloom filters.

I wasn't so sure this was because of dictionaries though.

_**Happy New Year**_

**Comment by asubiotto** [comment]
Yes, using arrow for cold storage is something we've thought about as well but decided not to do (at least for now) because of the lack of the indexing structures you mention.

With the current state of things though where we do need parquet -> arrow conversions what I mean is that we first read all the parquet values (which with dictionary encoding as I understand will materialize all the dictionary values): https://github.com/polarsignals/frostdb/blob/e3813ef7f4102b41524c0069ce7caf2ffb7e842f/pqarrow/arrow.go#L781

And then write them to arrow. I think there must be a better way to do this. For example for the plain bytes case we directly use the flat bytes slice + offsets (see `OptBinaryBuilder.AppendData`). Maybe there's a way to just get the dictionary values + index slice and construct an arrow array from those.

**Comment by gernest** [comment]
Thanks for the feedback. I have ran out of low hanging fruits to hack on `frostdb` . I will look into this.

**Comment by thorfour** [comment]
Some additional context about not choosing arrow IPC as the storage format. 

Arrow IPC base unit is the record batch. Which means if we just want to access a single column, we have to read the entire record into memory first, which is not going to be adequate for large historical queries.
