### ISSUE TITLE
not completely fixed https://github.com/polarsignals/frostdb/pull/662#issue-2056817397

### ISSUE THREAD

**Issue by jicanghaixb** [polarsignals/frostdb#663]
arrowutils/groupranges.go,merge.go and builder/utils.go has the same issue.

**Comment by gernest** [comment]
Please provide more details

- Describe what is the issue ?
- Show steps to reproduce the issue

This was I will be able to help you.

**Comment by jicanghaixb** [comment]
type Sample struct {
	Name         string            `frostdb:"name,rle_dict,asc(0)"`
	Duration     int64             `frostdb:"duration,rle_dict,asc(1)"`
	Labels       map[string]string `frostdb:"labels,rle_dict,asc(2),null_first"`
	Timestamp    int64             `frostdb:"timestamp,asc(3),lz4_raw,delta_binary_packed"`
	Value        float64           `frostdb:"value,plain,lz4_raw"`
}

i use sample build arrow.Record, than insert to frostdb. when i run ordered aggregation count(value) group by name, than return a error : "unsupported dictionary type: *array.String"

error locate in arrowutils/groupranges.go  
function name : GetGroupsAndOrderedSetRanges
case *array.Dictionary:
			switch dict := t.Dictionary().(type) {
			case *array.Binary:
				for j := 0; j < arr.Len(); j++ {
					var curGroupValue []byte
					if curGroup[i] != nil {
						curGroupValue = curGroup[i].([]byte)
					}
					vIsNull := t.IsNull(j)
					cmp, ok := nullComparison(curGroupValue == nil, vIsNull)
					if !ok {
						cmp = bytes.Compare(curGroupValue, dict.Value(t.GetValueIndex(j)))
					}
					if err := handleCmpResult(cmp, i, t, j); err != nil {
						return nil, nil, nil, err
					}
				}
                        default:
				panic(fmt.Sprintf("unsupported dictionary type: %T", dict))

**Comment by gernest** [comment]
@jicanghaixb thanks for the feedback. I have submitted a PR to address it .
