### ISSUE TITLE
records.Build can be moved out of internal packages, so that we can use it to directly build arrow.record?

### ISSUE THREAD

**Issue by jicanghaixb** [polarsignals/frostdb#674]

**Comment by gernest** [comment]
Direct use is discouraged, use `*frostdb.GenericTable[T]`  instead. It directly builds `arrow.Record`

**Comment by jicanghaixb** [comment]
I want to directly generate arrow.record on the client side instead of converting it to arrow.record on the server side,  improve the writing ability on the frostdb server side.

**Comment by gernest** [comment]
you are welcome!

**Comment by gernest** [comment]
@thorfour we can close this.
