### ISSUE TITLE
unsupport aggregation specific dynamic column

### ISSUE THREAD

**Issue by jicanghaixb** [polarsignals/frostdb#684]
When I defined value column as dynamic column, I use select sum(value)  group by labels.method that is ok, but I use select sum(value.request)  group by labels.method that return: 
<details><summary>Details</summary>
<p>
        invalid aggregation
        Aggregation [sum(value.request)] Group: [labels.method]
          TableScan Table: 3469660e-d808-44bf-baf3-006abef8751d Projection: [] Filter: <nil> Distinct: []
          -> invalid expression: column not found: value.request: sum(value.request)

</p>
</details> 

I found logicalplan/validate.go no support dynamic clolumn:
```go
		column, found := schema.ColumnByName(named.Name())
		if !found {
			return &ExprValidationError{
				message: fmt.Sprintf("column not found: %s", named.Name()),
				expr:    expr,
			}
		}
``` 
The above code may need to be modified to support specific dynamic columns

**Comment by thorfour** [comment]
Thank you for the report!
