### ISSUE TITLE
MergeRecords can  support array.Float64 sort?

### ISSUE THREAD

**Issue by jicanghaixb** [polarsignals/frostdb#720]
MergeRecords function is very useful. Thank you for providing this function. but now not support *array.Float64  sort, can we support it?

Also, could we add a reverse sorting function MergeReverseRecords？

**Comment by metalmatze** [comment]
Supporting float64 shouldn't be too difficult to add to the `Less` function: https://github.com/polarsignals/frostdb/blob/main/pqarrow/arrowutils/merge.go#L95-L142
We'd happily accept if you want to send a Pull Request. 

Adding reverse sorting to merging seems possible. We would need to discuss what the API change would look like or if we should add another function like you proposed. 

Do you have an example where [sorting the records](https://github.com/polarsignals/frostdb/blob/276211ce6995d8e68378d5d9495ffac5d980b008/pqarrow/arrowutils/sort.go#L53) first and then merging the record wouldn't work?
