### ISSUE TITLE
Proper transaction support

### ISSUE THREAD

**Issue by thorfour** [polarsignals/frostdb#721]
Transactions were originally added to FrostDB because we used to split writes up and sort each row of a write into different granules. The scan layer excludes transactions that have a higher tx number than the read is being performed with to avoid reading a partial write.

However today we do not split up writes so reads excluding `tx > read_tx` doesn't make as much as sense because it's still a consistent read we're just now artificially limiting the amount of data we read. 

I propose that we add proper database transactions to FrostDB such that we can atomically write to multiple tables at once. Potentially in the future support other database transactions as well such as queries, table creation/deletion etc.

API Proposal

```go
type Table interface {
    InsertRecord(context.Context, arrow.Record) error
}

type Transaction interface {
    GetTable(string) (Table, error)
    Commit()
    Abort()
}
  
type DB interface {
    ...
    Begin() Transaction
}
```

Which would allow for something like

```go

tx := db.Begin()
defer tx.Commit()
if err := tx.GetTable("table1").InsertRecord(ctx, r1); err != nil {
   tx.Abort()
   return
}
if err := tx.GetTable("table2").InsertRecord(ctx, r2); err != nil {
   tx.Abort()
   return
}
```

Multi-table transactions could be implemented quite easily by getting a write tx which already blocks reads from reading it as well as compactions from compacting it until it has been committed. In the event of an abort the transaction can walk back the writes and remove them from the L0 level of each table that they were written to before marking the transaction as complete. Thus still providing a consistent view.

**Comment by asubiotto** [comment]
I think multi-table transactions would only be beneficial in cases where we allow joining multiple tables. I'm very wary of adding joins to the DB (you introduce a world of complexity), so I'm simply not sure that explicit transactions would give us any benefits, but I might be missing something.

**Comment by thorfour** [comment]
> I think multi-table transactions would only be beneficial in cases where we allow joining multiple tables. I'm very wary of adding joins to the DB (you introduce a world of complexity), so I'm simply not sure that explicit transactions would give us any benefits, but I might be missing something.

What about the writes that are causally related? Like we have in production today where we write two tables and it has resulted in missing samples if one of the writes completes but the other does not?

**Comment by asubiotto** [comment]
True. That's what I was missing then.

**Comment by thorfour** [comment]
One thing required for this change to to change snapshots to respect the tx. Right now they snapshot whatever is in the index.
