### ISSUE TITLE
Add array operations

### ISSUE THREAD

**Issue by brancz** [polarsignals/frostdb#73]
While repeated types are now supported (#72) for writing and reading, they lack the ability to be filtered in more expressive ways than exact array matches (`==`) and not matches (`!=`). I don't think I have thought through the APIs enough yet for this, but one thought I've had is something like:

```
logicalplan.Col("values").Any().Eq(logicalplan.Literal(5)))
```

In this example, the table has a column called `values`, which is an array of integers, and the filter would keep only those rows whose `values` contain `5`.

I'm not sure I'm satisfied with the API, but I wanted to open this issue to at least drop my thoughts here.

**Comment by ostafen** [comment]
What do you think about adding a specific method for this, such as `ContainsAny()` (a `ContainsAll()` method could be also added)?
