### ISSUE TITLE
Add renovate to keep our dependencies up-to-date

### ISSUE THREAD

**Issue by metalmatze** [polarsignals/frostdb#758]
We've just noticed that some of our dependencies are very old. 
Renovate is amazing in the other repositories.

If you want to help, please send a Pull Request!

**Comment by elliotchenzichang** [comment]
raised a PR, could you help review it when you have time? Thanks！

**Comment by elliotchenzichang** [comment]
#763 raised another PR, add a script into makefile for this. That may be more effective.

**Comment by metalmatze** [comment]
Implemented via #774
