### ISSUE TITLE
arrowutils.mergeRecords function has an assertion error

### ISSUE THREAD

**Issue by jicanghaixb** [polarsignals/frostdb#767]
when i use arrowutils.mergeRecords to handle arrow.Record in frostdb logicalplan callback. return a asserttion errror:

<details><summary>Details</summary>
<p>

panic: interface conversion: arrow.Array is *array.Binary, not *array.String

goroutine 34934 [running]:
github.com/polarsignals/frostdb/pqarrow/builder.AppendValue({0x2e05060?, 0xc05aa895e8?}, {0x2e228a0, 0xc0b5278e40?}, 0x0)
        github.com/frostdb/pqarrow/builder/utils.go:76 +0xffd
github.com/polarsignals/frostdb/pqarrow/arrowutils.MergeRecords({0x2def118, 0x4ae0d20}, {0xc00249cd00, 0xe, 0x3?}, {0x4ae0d20, 0x0, 0x0}, 0x0)
       github.com/frostdb/pqarrow/arrowutils/merge.go:51 +0x485

</p>
</details> 

I found the reason:
```go
	type WeatherRecord struct {
		City     map[string]string `frostdb:",rle_dict,asc(0)"`
		Day      string            `frostdb:",rle_dict,asc(1)"`
		Snowfall float64
	}
``` 
I use frostdb.NewGenericTable to get table, than use table.Write to write sweatherrecord sample, WeatherRecord.Day in the memory is *array.String, but read from parquet file to arrow.Record, WeatherRecord.Day  is  *array.Binary, so when use frostdb query hot and cold data together, 
MergeRecords will generate an assertion error as mentioned above
```go
func MergeRecords(
	mem memory.Allocator,
	records []arrow.Record,
	orderByCols []SortingColumn,
	limit uint64,
) (arrow.Record, error) {
	h := cursorHeap{
		cursors:     make([]cursor, len(records)),
		orderByCols: orderByCols,
	}
	for i := range h.cursors {
		h.cursors[i].r = records[i]
	}

	schema := records[0].Schema()   // root cause
	recordBuilder := builder.NewRecordBuilder(mem, schema)
	defer recordBuilder.Release()
```

**Comment by gernest** [comment]
Interesting find, Indeed there is a mismatch between array type mapping on this regards. Mainly because we are a bit lax on what a string column can be, as such some cases we have `*array.Binary` and other cases `*array.String`.

From my understanding  it was mostly `*array.Binary` and `frostdb.NewGenericTable` was trying consolidate that and reflect the schema.

Unfortunately I didn't get to introduce `binary` columns in our schema, which would have solved this problem.

The idea was to write the schema like this.

```go
	type WeatherRecord struct {
		City     map[string]string `frostdb:",rle_dict,asc(0),binary"`
		Day      string            `frostdb:",rle_dict,asc(1),binary"`
		Snowfall float64
	}
```

Which explicitly states to treat those columns as `*array.Binary`.

I'm not sure I can be of much help, just wondering how/why were you using `MergeRecord` directly ? Because I am pretty sure the query engine will work fine with your schema as it is.

**Comment by jicanghaixb** [comment]
> Interesting find, Indeed there is a mismatch between array type mapping on this regards. Mainly because we are a bit lax on what a string column can be, as such some cases we have `*array.Binary` and other cases `*array.String`.
> 
> From my understanding it was mostly `*array.Binary` and `frostdb.NewGenericTable` was trying consolidate that and reflect the schema.
> 
> Unfortunately I didn't get to introduce `binary` columns in our schema, which would have solved this problem.
> 
> The idea was to write the schema like this.
> 
> ```go
> 	type WeatherRecord struct {
> 		City     map[string]string `frostdb:",rle_dict,asc(0),binary"`
> 		Day      string            `frostdb:",rle_dict,asc(1),binary"`
> 		Snowfall float64
> 	}
> ```
> 
> Which explicitly states to treat those columns as `*array.Binary`.
> 
> I'm not sure I can be of much help, just wondering how/why were you using `MergeRecord` directly ? Because I am pretty sure the query engine will work fine with your schema as it is.

thks your reply

I use arrowutils.MergeRecords because I  need to sort the results, so I need to merge the query arrow records first and then sort them.

by the way, I found ordered_aggregate.go also use arrowutils.MergeRecords fuction, maybe has same issue.
```go
func (a *OrderedAggregate) Finish(ctx context.Context) error {
       ......
	if len(records) == 1 {
		if err := a.next.Callback(ctx, records[0]); err != nil {
			return err
		}
	} else {
		// The aggregation results must be merged.
		orderByCols := make([]int, len(a.groupColOrdering))
		for i := range orderByCols {
			orderByCols[i] = i
		}
		mergedRecord, err := arrowutils.MergeRecords(a.pool, records, orderByCols, 0)
		if err != nil {
			return err
		}
```
