### ISSUE TITLE
There is an issue with the current snapshot losing some ManifestEntry when Iceberg concurrently executes uploads

### ISSUE THREAD

**Issue by jicanghaixb** [polarsignals/frostdb#891]
The current iceberg runs the Upload function concurrently (when frost db quickly injects data), There is competition leading to partial loss of data in the current snapshot's ManifestEntry, maybe Upload need add a lock

**Comment by thorfour** [comment]
Nevermind I assume that you're likely using the HDFS catalog, which isn't meant for concurrent writers. I think we can simply add a lock to the snapshot writer of the hdfs catalog.

**Comment by jicanghaixb** [comment]
Thanks, I wrap Iceberg and added an upload lock to avoid the issue
