### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by bliiitz** [polarsignals/frostdb#935]
Hi,
I'm interested to use this database in one of my project and I have few questions:
- Is it continued to be maintained ?
- Is it ready for production ? what is your experience with it on your epimetheus production ?

I've planned to use it to store EVM logs and transactions to have a long terme immutable storage with great storage compression and large read performance

cheers

**Comment by thorfour** [comment]
Hello, glad your interested in FrostDB!

Yes it is still currently maintained, but it is in more of a maintenance mode right now. 

It is ready for production, we currently run it at scale in production however we've put in a lot of work on top of it in our production environment to horizontally scale it. So depending on how large a system you're building, a single FrostDB may not be the best choice.

**Comment by brancz** [comment]
One more clarification. Epimetheus was mostly a demo to show that frostdb can be used in other scenarios than what we use it for (profiling data in the case of Parca/Polar Signals). We wouldn’t recommend using Epimetheus in production.

**Comment by bliiitz** [comment]
Thanks for you answers :)

In my case, i don't think there will be heavy loads on write (just scanning blockchains and store txs /events) but i'll probably have load on read. 

`we've put in a lot of work on top of it in our production environment to horizontally scale it` is it closed source ?

**Comment by thorfour** [comment]
For now the horizontal scaling is closed source. We may open source it in the future, but there is no timeline for doing so.
