### ISSUE TITLE
link parquet-go failed on go 1.23

### ISSUE THREAD

**Issue by f2w00** [polarsignals/frostdb#938]
# WhatHappend

After upgrading my Golang toolchain to 1.23 on my Manjaro machine, run the example

[[frostdb/examples/simple/simple.go](https://github.com/polarsignals/frostdb/blob/ee6970eff139c58a45998a87c02b661f32be5cbe/examples/simple/simple.go#L17-L69)](https://github.com/polarsignals/frostdb/blob/ee6970eff139c58a45998a87c02b661f32be5cbe/examples/simple/simple.go#L17-L69) but fails:

```bash
link: github.com/parquet-go/parquet-go/hashprobe/aeshash: invalid reference to runtime.aeskeysched
```

```bash
go version                                                                                                                                                         ✔
go version go1.23.1 linux/amd64
```

# Mayhelp

According to [[parquet-go/parquet-go#142](https://github.com/parquet-go/parquet-go/pull/142)](https://github.com/parquet-go/parquet-go/pull/142) the root cause probably is this change from [[Go 1.23](https://tip.golang.org/doc/go1.23#linker)](https://tip.golang.org/doc/go1.23#linker):

> The linker now disallows using a //go:linkname directive  to refer to internal symbols in the standard library (including the  runtime) that are not marked with //go:linkname on their definitions.  Similarly, the linker disallows references to such symbols from assembly code. For backward compatibility, existing usages of //go:linkname  found in a large open-source code corpus remain supported. Any new  references to standard library internal symbols will be disallowed.

According to [[grafana/pyroscope#3485](https://github.com/grafana/pyroscope/issues/3485)](https://github.com/grafana/pyroscope/issues/3485) this can be fixed by upgrading  `parquet-go` to `v0.23.0`

**Comment by asubiotto** [comment]
Thanks for the reminder. #939 should fix this.
